# version: '3.8'

services:

  # mysql:
  #   image: mysql
  #   container_name: verdelia-db
  #   restart: always
  #   command: --max_allowed_packet=256M --init-file /data/application/init.sql

  #   environment:
  #     MYSQL_DATABASE: verdelia
  #     MYSQL_USER: dev_user
  #     MYSQL_ROOT_PASSWORD: dev_password
  #     MYSQL_PASSWORD: dev_password
  #   expose:
  #     - 3306
  #   volumes:
  #     - ./mysql/model.sql:/data/application/init.sql
  #     - ./data:/var/lib/mysql
  #   networks:
  #     - verdelia-net
  verdelia-api:
    container_name: verdelia-api-test
    hostname: verdelia-api-test
    restart: unless-stopped
    build:
      context: api_server/
      dockerfile: Dockerfile.test
      # cmd : "pytest"
      # args:
        # - API_PORT=9000
    image: omarzos/verdelia-api-test
    environment:
      - API_PORT=9000
      - SQL_SCHEMA=mysql+pymysql
      - SQL_HOST=verdelia-db
      - SQL_DATABASE=verdelia
      - SQL_USER=dev_user
      - SQL_PASSWORD=dev_password
      - SQL_PORT=3306
      - AUTH_PORT=9090
      - AUTH_SERVER_NAME=verdelia-auth
      - AUTH_REGISTRATION_ENDPOINT=/auth/users/
      - AUTH_LOGIN_ENDPOINT=${AUTH_LOGIN_ENDPOINT}
      - AUTH_DELETE_ENDPOINT=${AUTH_DELETE_ENDPOINT}
      - ALGORITHM=${ALGORITHM}
      - API_SECRET_KEY=${SECRET_KEY}
      - FILE_UPLOAD_ENDPOINT=/fs/upload
      - FS_HOST=verdelia-fs
      - FS_PORT=9099
      - API_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - API_GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - API_FACEBOOK_CLIENT_ID=${FACEBOOK_CLIENT_ID}
      - API_FACEBOOK_CLIENT_SECRET=${FACEBOOK_CLIENT_SECRET}
      - API_INSTAGRAM_CLIENT_ID=${INSTAGRAM_CLIENT_ID}
      - API_INSTAGRAM_CLIENT_SECRET=${INSTAGRAM_CLIENT_SECRET}
      - AUTH_CHANGE_ENDPOINT=${AUTH_CHANGE_ENDPOINT}
    networks:
      - verdelia-net
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
    # labels:
    #   - "traefik.enable=true"
    #   # - "traefik.docker.network=verdelia-net"  # Critical fix
    #   - "traefik.http.routers.verdelia-api.rule=Host(`verdelia.com`) && PathPrefix(`/api`)"
    #   - "traefik.http.routers.verdelia-api.entrypoints=websecure"
    #   - "traefik.http.routers.verdelia-api.tls=true"
    #   - "traefik.http.routers.verdelia-api.tls.certresolver=letsencrypt"
    #   - "traefik.http.services.verdelia-api.loadbalancer.server.port=9000"

  # verdelia-auth:
  #   container_name: verdelia-auth
  #   hostname: verdelia-auth
  #   restart: unless-stopped
  #   # build:
  #     # context: auth_server/
  #     # args:
  #       # - AUTH_PORT=9090
  #   image: omarzos/verdelia-auth
  #   environment:
  #     - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
  #     - AUTH_PORT=9090
  #     - API_SECRET_KEY=${SECRET_KEY}
  #     - API_ALGORITHM=${ALGORITHM}
  #     - AUTH_DATABASE_URL=sqlite:///../auth_db/auth_db_data.db
  #   networks:
  #     - verdelia-net
  #   volumes:
  #     - ./auth_server/:/code
  #     - ./auth_db/:/auth_db/
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.5'
  #         memory: 256M
  #   # labels:
  #   #   - "traefik.enable=true"
  #   #   - "traefik.http.routers.verdelia-auth.rule=Host(`verdelia.com`) && PathPrefix(`/auth`)"
  #   #   - "traefik.http.routers.verdelia-auth.entrypoints=websecure"
  #   #   - "traefik.http.routers.verdelia-auth.tls=true"
  #   #   - "traefik.http.routers.verdelia-auth.tls.certresolver=letsencrypt"
  #   #   - "traefik.http.services.verdelia-auth.loadbalancer.server.port=9090"

  # verdelia-fs:
  #   container_name: verdelia-fs
  #   hostname: verdelia-fs
  #   restart: unless-stopped
  #   # build:
  #     # context: file_server/
  #     # args:
  #       # - FS_PORT=9099
  #   image: omarzos/verdelia-fs
  #   environment:
  #     - FS_PORT=9099
  #   networks:
  #     - verdelia-net
  #   volumes:
  #     - ./file_server/:/code
  #     - ./fs/:/fs/
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.5'
  #         memory: 512M
  #   # labels:
  #   #   - "traefik.enable=true"
  #   #   - "traefik.http.routers.verdelia-fs.rule=Host(`verdelia.com`) && PathPrefix(`/fs`)"
  #   #   - "traefik.http.routers.verdelia-fs.entrypoints=websecure"
  #   #   - "traefik.http.routers.verdelia-fs.tls=true"
  #   #   - "traefik.http.routers.verdelia-fs.tls.certresolver=letsencrypt"
  #   #   - "traefik.http.services.verdelia-fs.loadbalancer.server.port=9099"

  # # traefik:
  # #   image: traefik:v2.10
  # #   container_name: traefik
  # #   restart: unless-stopped
  # #   security_opt:
  # #     - no-new-privileges:true
  # #   command:
  # #     - "--api.insecure=true"
  # #     - "--providers.docker=true"
  # #     - "--providers.docker.exposedbydefault=true"
  # #     - "--entrypoints.web.address=:80"
  # #     - "--entrypoints.websecure.address=:443"
  # #     - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
  # #     - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
  # #     - "--certificatesresolvers.letsencrypt.acme.email=osjfvhng16@gmail.com"
  # #     - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
  # #     - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
  # #     - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      
  # #     # - "--providers.docker.network=verdelia-net"  # Explicit network
  # #     - "--certificatesresolvers.letsencrypt.acme.dnschallenge=true"
  # #     - "--certificatesresolvers.letsencrypt.acme.dnschallenge.provider=digitalocean"
  # #     - "--certificatesresolvers.letsencrypt.acme.dnschallenge.delaybeforecheck=30"
  # #   environment:
  # #     - "DO_AUTH_TOKEN=${DO_API_TOKEN}"  # DigitalOcean API token
  # #   ports:
  # #     - "80:80"
  # #     - "443:443"
  # #     - "8080:8080"
  # #   networks:
  # #     - verdelia-net
  # #   volumes:
  # #     - "./letsencrypt:/letsencrypt"
  # #     - "/var/run/docker.sock:/var/run/docker.sock:ro"
  # #   labels:
  # #     - "traefik.enable=true"
  # #     # - "traefik.http.routers.traefik.rule=Host(`traefik.verdelia.com`)"
  # #     - "traefik.http.routers.traefik.service=api@internal"
  # #     - "traefik.http.routers.traefik.entrypoints=websecure"
  # #     # - "traefik.http.routers.traefik.tls=true"
  # #     # - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
  # #     # - "traefik.http.routers.traefik.middlewares=traefik-auth"
  # #     # - "traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_AUTH_CREDENTIALS}"

networks:
  verdelia-net:
    name: verdelia-net
    driver: bridge
    attachable: true