# version: '3.8'

# Dev mode only!!!

services:

  # prometheus:
  #   image: prom/prometheus
  #   container_name: prometheus
  #   restart: unless-stopped

  #   ports:
  #     - "9091:9090"

  #   volumes:
  #     - ./setup/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  #   networks:
  #     - verdelia-net

  # rabbitmq:
  #   image: rabbitmq:3.13-management-alpine
  #   container_name: rabbitmq
  #   hostname: rabbitmq
  #   restart: unless-stopped
    
  #   ports:
  #     - "5672:5672"   # AMQP protocol port
  #     - "15672:15672" # Management UI port
  #     - "15692:15692" # Prometheus metrics port (optional)
    
  #   environment:
  #     # Default credentials (CHANGE THESE IN PRODUCTION!)
  #     RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-admin}
  #     RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:-admin123}
  #     RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST:-/}
      
  #     # Memory and disk thresholds
  #     # RABBITMQ_VM_MEMORY_HIGH_WATERMARK: 0.6
  #     RABBITMQ_DISK_FREE_LIMIT: 2GB
      
  #     # Erlang cookie for clustering (required for multi-node setup)
  #     RABBITMQ_ERLANG_COOKIE: "super-secret-cookie-change-me"
      
  #     # Server additional configuration
  #     RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648"
    
  #   volumes:
  #     # Persist data
  #     - ./volumes/rabbitmq/data:/var/lib/rabbitmq
  #     - ./volumes/rabbitmq/logs:/var/log/rabbitmq
      
  #     # Custom configuration (optional)
  #     - ./setup/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
  #     - ./setup/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
  #     - ./setup/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins:ro
    
    
  #   healthcheck:
  #     test: rabbitmq-diagnostics -q ping
  #     interval: 30s
  #     timeout: 10s
  #     retries: 5
  #     start_period: 40s
    
  #   labels:
  #     - "traefik.enable=false"



  #   networks:
  #     - verdelia-net

  # verdelia-web:
  #   container_name: verdelia-web
  #   hostname: verdelia-web
  #   image: verdelia-web:latest
  #   restart: unless-stopped
  #   ports:
  #     - 9070:9070
  #   networks:
  #     - verdelia-net
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '1'
  #         memory: 512M

  mysql:
    image: mysql
    container_name: verdelia-db
    restart: always
    command: --max_allowed_packet=256M --init-file /data/application/init.sql

    environment:
      MYSQL_DATABASE: ${SQL_DATABASE}
      MYSQL_USER: ${SQL_USER}
      MYSQL_ROOT_PASSWORD: ${SQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${SQL_PASSWORD}
      
    ports:
      - ${SQL_PORT}:3306
    volumes:
      - ./setup/mysql/model.sql:/data/application/init.sql
      - ./volumes/data:/var/lib/mysql
    networks:
      - verdelia-net
  verdelia-api:
    container_name: verdelia-api
    hostname: verdelia-api
    restart: unless-stopped
    build:
      context: ./api_server
      dockerfile: ./Dockerfile.dev
      args:
        - API_PORT=${API_PORT}
    command: uvicorn server:app --host 0.0.0.0 --port ${API_PORT} --reload
    image: omarzos/verdelia-api
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      - API_PORT=${API_PORT}
      - SQL_SCHEMA=${SQL_SCHEMA}
      - SQL_HOST=${SQL_HOST}
      - SQL_DATABASE=${SQL_DATABASE}
      - SQL_USER=${SQL_USER}
      - SQL_PASSWORD=${SQL_ROOT_PASSWORD}
      - SQL_PORT=3306
      - AUTH_PORT=${AUTH_PORT}
      - AUTH_SERVER_NAME=${AUTH_SERVER_NAME}
      - AUTH_REGISTRATION_ENDPOINT=${AUTH_REGISTRATION_ENDPOINT}
      - AUTH_LOGIN_ENDPOINT=${AUTH_LOGIN_ENDPOINT}
      - AUTH_DELETE_ENDPOINT=${AUTH_DELETE_ENDPOINT}
      - AUTH_ALGORITHM=${AUTH_ALGORITHM}
      - AUTH_SECRET_KEY=${AUTH_SECRET_KEY}
      - API_ALGORITHM=${API_ALGORITHM}
      - API_SECRET_KEY=${API_SECRET_KEY}
      - AUTH_CHANGE_ENDPOINT=${AUTH_CHANGE_ENDPOINT}
      - FILE_UPLOAD_ENDPOINT=${FILE_UPLOAD_ENDPOINT}
      - FS_HOST=${FS_HOST}
      - FS_PORT=${FS_PORT}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
      - RABBITMQ_VHOST=${RABBITMQ_VHOST}
      - REFRESH_TOKEN_EXPIRE_DAYS=${REFRESH_TOKEN_EXPIRE_DAYS}
      - AUTH_SERVER_PROTOCOLE=${AUTH_SERVER_PROTOCOLE}
      - DEFAULT_ADMIN_USERNAME=${DEFAULT_ADMIN_USERNAME}
      - DEFAULT_ADMIN_PASSWORD=${DEFAULT_ADMIN_PASSWORD}
      - SILO_SERVER_PROTOCOLE=${SILO_SERVER_PROTOCOLE}
      - SILO_SERVER_NAME=${SILO_SERVER_NAME}
      - SILO_SERVER_PORT=${SILO_SERVER_PORT}
      - SILO_SERVER_PREFIX=${SILO_SERVER_PREFIX}
      - FINANCE_SERVER_PROTOCOLE=${FINANCE_SERVER_PROTOCOLE}
      - FINANCE_SERVER_NAME=${FINANCE_SERVER_NAME}
      - FINANCE_SERVER_PORT=${FINANCE_SERVER_PORT}
      - FINANCE_SERVER_PREFIX=${FINANCE_SERVER_PREFIX}
      
    networks:
      - verdelia-net
    volumes:
      - ./api_server:/code
    
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
  
  verdelia-auth:
    container_name: verdelia-auth
    hostname: verdelia-auth
    restart: unless-stopped
    command: uvicorn server:app --host 0.0.0.0 --port ${AUTH_PORT} --reload # 
    image: omarzos/emastan-auth:latest
    environment:
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - AUTH_PORT=${AUTH_PORT}
      - API_SECRET_KEY=${AUTH_SECRET_KEY}
      - API_ALGORITHM=${AUTH_ALGORITHM}
      - AUTH_DATABASE_URL=sqlite:///../auth_db/auth_db_data.db
      - DEFAULT_ADMIN_USERNAME=${DEFAULT_ADMIN_USERNAME}
      - DEFAULT_ADMIN_PASSWORD=${DEFAULT_ADMIN_PASSWORD}
    ports:
      - ${AUTH_PORT}:${AUTH_PORT}
    networks:
      - verdelia-net
    # volumes:
    #   - ./volumes/auth_db/:/auth_db/
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

  verdelia-finance:
    container_name: verdelia-finance
    hostname: verdelia-finance
    restart: unless-stopped
    command: uvicorn server:app --host 0.0.0.0 --port ${FINANCE_SERVER_PORT} --reload
    image: omarzos/finance-api:latest
    ports:
      - ${FINANCE_SERVER_PORT}:${FINANCE_SERVER_PORT}
    environment:
      - FINANCE_PORT=${FINANCE_SERVER_PORT}
      - SQL_SCHEMA=${SQL_SCHEMA}
      - SQL_HOST=${SQL_HOST}
      - SQL_USER=${SQL_USER}
      - SQL_PASSWORD=${SQL_PASSWORD}
      - SQL_DATABASE=${SQL_DATABASE}
      - SQL_PORT=3306
    networks:
      - verdelia-net
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  verdelia-silo:
    container_name: verdelia-silo
    hostname: verdelia-silo
    restart: unless-stopped
    command: uvicorn server:app --host 0.0.0.0 --port ${SILO_SERVER_PORT} 
    image: omarzos/esilo-api:latest
    ports:
      - ${SILO_SERVER_PORT}:${SILO_SERVER_PORT}
    environment:
      - ESILO_PORT=${SILO_SERVER_PORT}
      - SQL_SCHEMA=${SQL_SCHEMA}
      - SQL_HOST=${SQL_HOST}
      - SQL_USER=${SQL_USER}
      - SQL_PASSWORD=${SQL_PASSWORD}
      - SQL_DATABASE=${SQL_DATABASE}
      - SQL_PORT=3306
    networks:
      - verdelia-net
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  verdelia-fs:
    container_name: verdelia-fs
    hostname: verdelia-fs
    restart: unless-stopped
    command: uvicorn server:app --host 0.0.0.0 --port ${FS_PORT} --reload
    image: omarzos/emagrad-fs:latest
    ports:
      - ${FS_PORT}:${FS_PORT}
    environment:
      - FS_PORT=${FS_PORT}
      - FS_BASE_STORAGE=${FS_BASE_STORAGE}
      - FS_CACHE_STORAGE=${FS_CACHE_STORAGE}
    networks:
      - verdelia-net
    # volumes:
    #   - ./volumes/fs/:/fs/
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  # verdelia-stream:
  #   container_name: verdelia-stream
  #   hostname: verdelia-stream
  #   restart: unless-stopped
  #   command: uvicorn server:app --host 0.0.0.0 --port 9097 --reload
  #   image: omarzos/asif-stream
  #   ports:
  #     - 9097:9097
  #   environment:
  #     - FS_PORT=9097
  #   networks:
  #     - verdelia-net
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.5'
  #         memory: 512M

volumes:
  volumes:
    driver: local


networks:
  verdelia-net:
    name: verdelia-net
    driver: bridge