@startuml
skinparam componentStyle rectangle
skinparam shadowing false

package "Client Layer" {
  [verdelia-web]
  [verdelia-mobile]
}

package "Core Services" {
  [verdelia-api]
  [verdelia-auth]
  [verdelia-stream]
  [verdelia-fs]
}


package "Infrastructure" {
  [rabbitmq]
  [verdelia-db]
}

[verdelia-web] --> [verdelia-api] : REST / HTTPS
[verdelia-mobile] --> [verdelia-api] : REST / HTTPS

[verdelia-web] --> [verdelia-stream] : WebSocket / SSE
[verdelia-mobile] --> [verdelia-stream] : Realtime

[verdelia-api] --> [verdelia-auth]
[verdelia-api] --> [verdelia-db]
[verdelia-api] --> [verdelia-fs]
[verdelia-api] --> [rabbitmq]

[verdelia-stream] --> [rabbitmq]

@enduml
