global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "verdelia-api"
    static_configs:
      - targets: ["verdelia-api:9000"]

  - job_name: "verdelia-auth"
    scheme: https

    tls_config:
      insecure_skip_verify: true

    static_configs:
      - targets: ["verdelia-auth:9090"]

  - job_name: "verdelia-fs"
    static_configs:
      - targets: ["verdelia-fs:9099"]

  - job_name: "verdelia-stream"
    static_configs:
      - targets: ["verdelia-stream:9097"]

  - job_name: "rabbitmq"
    static_configs:
      - targets: ["rabbitmq:15692"]